export const PROVIDE_KEY = {
  VAI: Symbol("VAI"),
  CREATE_VAI: Symbol("CREATE_VAI"),
  PAGE_STATUS: Symbol("PAGE_STATUS"),
  ROUTE_STATUS: Symbol("ROUTE_STATUS"),
  VUE_ITEM_STORE: Symbol("VUE_ITEM_STORE"),
  VUE_ITEM_INDEX: Symbol("VUE_ITEM_INDEX"),
  ROUTER_WAITER: Symbol("ROUTER_WAITER"),
  AGENT_EVENT: Symbol("AGENT_EVENT"),
  LAYER_STORE: Symbol("LAYER_STORE"),
  LAYER_INDEX: Symbol("LAYER_INDEX"),
}
