export const PROVIDE_KEY = {
  VAI: Symbol("VAI"),
  CREATE_VAI: Symbol("CREATE_VAI"),
  PAGE_STATUS: Symbol("PAGE_STATUS"),
  ROUTE_STATUS: Symbol("ROUTE_STATUS"),
  VUE_ELEMENT_STORE: Symbol("VUE_ELEMENT_STORE"),
}
